config/routes.rb
Rails.application.routes.draw do
  get 'galaxy_vacansies/search'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :expeditions do
    get 'react', on: :collection
  end
  resources :planets
  resources :spaceships do
    get 'react', on: :collection
  end
  resources :galaxies
  resources :itinerary_entries
  resources :itineraries
  get 'chats/index', to: 'chats#index'
  post 'chats/new_message', to: 'chats#new_message'

  root "expeditions#index"

  scope module: 'api' do
    namespace 'v1' do
      resources :expeditions, only: %I[show index create]
    end
    namespace 'v2' do
      resources :spaceships, only: %I[show index create]
      resources :expeditions
      devise_for :users
    end
  end
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
  validates :title, presence: true, length: { in: 5..20 }
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  before_action :set_galaxy, except: [:new, :create, :index]

  def new
    @galaxy = Galaxy.new
  end

  def create
    @galaxy = Galaxy.new(galaxy_params)
    if @galaxy.save
      redirect_to galaxies_path, notice: 'Сохранение прошло успешно'
    else
      flash[:alert] = 'Во время сохранения произошли ошибки'
      render :new
    end
  end

  def index
    @galaxies = Galaxy.all
  end

  def edit
  end

  def update
    if @galaxy.update galaxy_params
      redirect_to galaxy_path, notice: 'Successfully saved'
    else
      flash[:alert] = 'Errors appeared while saving'
      render :edit
    end
  end

  def destroy
    @galaxy.destroy
    if @galaxy.destroyed?
      flash[:notice] = 'Destroyed successfully'
    else
      flash[:alert] = 'Error appeared while destroying'
    end
    redirect_to galaxies_path
  end

  def show
  end

  private

  def galaxy_params
    params.require(:galaxy).permit(:title)
  end

  def set_galaxy
    @galaxy = Galaxy.find(params[:id])
  end
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/views/galaxies/_form.html.erb
<div class="container">
  <%= simple_form_for @galaxy do |form| %>
    <%= form.input :title %>
    <%#= form.input :velocity, as: :float %>
    <%#= form.association :expedition, collection: Expedition.all, label_method: :title, value_method: :id %>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/galaxies/create.html.erb
<h1>Galaxies#create</h1>
<p>Find me in app/views/galaxies/create.html.erb</p>

app/views/galaxies/edit.html.erb
<h2>Editing Galaxy</h2>
<%= render 'form' %>

app/views/galaxies/index.html.erb
<h1>Galaxies List</h1>
<ul>
  <% @galaxies.each do |galaxy| %>
    <li>
      <%= galaxy.title %> <br>
      <%= link_to 'Show', galaxy_path(galaxy), class: 'btn btn-link' %>
    </li>
  <% end %>
</ul>
<%= link_to 'Create Galaxy', new_galaxy_path, class: 'btn btn-success' %>

app/views/galaxies/new.html.erb
<h1>Create Galaxy</h1>
<%= render 'form' %>

app/views/galaxies/show.html.erb
<h2>Galaxy <%= @galaxy.title %></h2>
<div>
  <strong>title = </strong>
  <%= @galaxy.title %>
</div>
<%= link_to 'Edit', edit_galaxy_path(@galaxy), class: 'btn btn-warning' %>
<%= link_to 'Delete', galaxy_path(@galaxy), class: 'btn btn-danger',
            method: :delete, data: { confirm: 'Are you sure?' } %>