config/routes.rb
Rails.application.routes.draw do
  get 'galaxy_vacansies/search'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :expeditions do
    get 'react', on: :collection
  end
  resources :planets
  resources :spaceships do
    get 'react', on: :collection
  end
  resources :galaxies
  resources :itinerary_entries
  resources :itineraries
  get 'chats/index', to: 'chats#index'
  post 'chats/new_message', to: 'chats#new_message'

  root "expeditions#index"

  scope module: 'api' do
    namespace 'v1' do
      resources :expeditions, only: %I[show index create]
    end
    namespace 'v2' do
      resources :spaceships, only: %I[show index create]
      resources :expeditions
      devise_for :users
    end
  end
end

app/models/expedition.rb
class Expedition < ApplicationRecord
  has_one :itinerary, dependent: :destroy
  has_many :spaceships, dependent: :destroy
  has_many :users

  validates :title, :description, presence: true
  validates :title, length: { in: 5..50 }
  validates :description, length: { in: 10..500 }

  after_create :create_assocs

  private

  def create_assocs
    create_itinerary(distance: 0.0)
  end
end

app/controllers/api/v1/expeditions_controller.rb
module Api::V1
  class ExpeditionsController < ApiController

  end
end

app/controllers/api/v2/expeditions_controller.rb
module Api::V2
  class ExpeditionsController < ApiController
    before_action :set_expedition, only: %I[show update destroy]

    def show
      render json: ::V2::ExpeditionSerializer.new(Expedition.find params[:id]).serialized_json
    end

    def update
      if @expedition.update(expedition_params)
        render json: @expedition, status: :ok
      else
        render json: { errors: @expedition.errors }, status: :unprocessable_entity
      end
    end

    def destroy
      @expedition.destroy
      if @expedition.destroyed?
        render json: 'delete successfully'
      else
        render json: 'delete aborted'
      end
    end

    private

    def set_expedition
      if Expedition.where(id: params[:id]).exists?
        @expedition = Expedition.find params[:id]
      else
        render json: 'expedition not exist!'
      end
    end
  end
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController
  before_action :set_model, except: [:new, :create, :index, :react]
  # skip_before_action :authenticate_user!
  after_action :create_notifier, only: %I[create]
  after_action :destroy_notifier, only: %I[destroy]

  def index
    authorize Expedition
    @expeditions = Expedition.all
    respond_to do |format|
      format.html
      format.json { render json: @expedition }
    end
  end

  def new
    authorize Expedition
    @expedition = Expedition.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def create
    authorize Expedition
    @expedition = Expedition.new(expedition_params)
    if @expedition.save
      respond_to do |format|
        format.html { redirect_to expeditions_path, notice: 'Сохранение прошло успешно' }
        format.js
      end
    else
      flash[:alert] = 'Во время сохранения произошли ошибки'
      render :new
    end
  end

  def edit
  end

  def update
    if @expedition.update expedition_params
      redirect_to expeditions_path, notice: 'Сохранение прошло успешно'
    else
      flash[:alert] = 'Во время сохранения произошли ошибки'
      render :edit
    end
  end

  def destroy
    @expedition.destroy
    respond_to do |format|
      format.html do
        if @expedition.destroyed?
          flash[:notice] = 'Удалено'
        else
          flash[:alert] = 'Ошибка удаления'
        end
        redirect_to expeditions_path
      end
      format.js
    end
  end

  private

  def set_model
    @expedition = Expedition.find params[:id]
    authorize @expedition
  end

  def expedition_params
    params.require(:expedition).permit(:title, :description)
  end

  def create_notifier
    ActionCable.server.broadcast ExpeditionsChannel::TITLE,
                                 partial: render_to_string(
                                     partial: "expeditions/expedition", object: @expedition
                                 ),
                                 action: :create.to_s,
                                 id: @expedition.id
  end

  def destroy_notifier
    ActionCable.server.broadcast ExpeditionsChannel::TITLE,
                                 partial: render_to_string(
                                     partial: 'expeditions/expedition', object: @expedition
                                 ),
                                 action: :destroy.to_s,
                                 id: @expedition.id
  end
end

app/helpers/expedition_helper.rb
module ExpeditionHelper
end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
end

app/views/expeditions/_expedition.html.erb
<div id="expedition_<%= expedition.id %>">
  <h2><%= expedition.title %></h2>
  <p><%= expedition.description %></p>
  <%= link_to 'Show', expedition_path(expedition) %>
  <%= link_to 'Delete', expedition_path(expedition), remote: true, method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
</div>

app/views/expeditions/_form.html.erb
<div class="container" id="new-expedition-form">
  <% url = @expedition.new_record? ? url_for(controller: 'expeditions', action: 'create', method: 'post') : url_for(controller: 'expeditions', action: 'update', method: 'put') %>
  <%= simple_form_for @expedition, remote: true, url: url do |form| %>
    <%= form.input :title %>
    <%= form.input :description %>
    <%#= form.association :expedition, collection: Expedition.all, label_method: :title, value_method: :id %>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" id="close-expedition" data-dismiss="modal">Close</button>
      <%= form.submit class: "btn btn-primary", id: 'create-expedition' %>
    </div>
  <% end %>
</div>

app/views/expeditions/create.js.erb
console.log('create expedition ajax')
$(function () {
    $('.expedition-list').prepend('<%= escape_javascript(render @expedition) %>');
    $('#new-expedition-form').remove();
});

app/views/expeditions/destroy.js.erb
console.log('ajax ответ')
$(function() {
   $('#expedition_<%= @expedition.id %>').remove();
});

app/views/expeditions/edit.html.erb
<h2>Edit Expedition</h2>
<%= render 'form' %>

app/views/expeditions/index.html.erb
<h1>Expeditions List:</h1>
<% if policy(Expedition).new? %>
  <p><%= link_to 'Create Expedition', new_expedition_path, remote: true, class: 'btn btn-success' %></p>
<% end %>
<div class="expedition-list">
  <%= render partial: "expeditions/expedition", collection: @expeditions %>
</div>
<%= link_to 'dom', '#', id: 'dom' %>

<%= render 'shared/slider' %>

app/views/expeditions/new.html.erb
<%= render 'form' %>

app/views/expeditions/new.js.erb
$(function () {
    if (!$('div.container').children().hasClass('simple_form new_expedition')) {
        $('.expedition-list').before('<%= escape_javascript(render('form')) %>')
    }
    else {
        console.log('class present')
    }

    $('#close-expedition').on('click', closeExpedition);

    function closeExpedition(event) {
        event.preventDefault();
        $('#new-expedition-form').remove();
    }
})

app/views/expeditions/react.html.erb
<h1>before react</h1>
<%#= javascript_pack_tag 'hello_react' %>

app/views/expeditions/show.html.erb
<h2>Expedition: "<%= @expedition.title %>" info:</h2>
<h4>Planets:</h4>
<ul>
<% @expedition.itinerary.planets.each do |planet| %>
  <li>
    <%= link_to planet.title, planet_path(planet) %>
    <%= '| distance: ' + planet.distance.to_s %>
  </li>
<% end %>
</ul>
<p><strong>Distance: </strong><%= @expedition.itinerary.distance_length %></p>
<p>Team:</p>
<ul style="list-style-type: none" class="list-group">
<% @expedition.users.each do |user| %>
  <li class="list-group-item">
    <%= image_tag "https://secure.gravatar.com/avatar/#{Digest::MD5.hexdigest user.email}" %>
    <%= user.email %> - <%= user.role %>
  </li>
<% end %>
</ul>
<p>
  <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Spacehips List:
  </a>
</p>
<div class="collapse" id="collapseExample">
    <table class="table table-striped table-bordered table-sm">
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
      </thead>
      <tbody>
  <% @expedition.spaceships.each do |spaceship| %>
      <tr>
        <td><%= link_to spaceship.title, spaceship_path(spaceship) %></td>
        <td><%= link_to 'Edit', edit_spaceship_path(spaceship), class: "btn btn-warning" %></td>
        <td><%= button_to 'Delete', spaceship_path(spaceship), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></td>
      </tr>
  <% end %>
      </tbody>
      </table>
</div>
<div style="text-align:left">
  <div class="row">
    <div class="col-2"><%= link_to 'Add Planets', new_itinerary_entry_path, class: "btn btn-success" %></div>
    <div class="col-2"><%= link_to 'Edit Expedition', edit_expedition_path(@expedition), class: "btn btn-warning" %></div>
    <div class="col-2"><%= link_to 'Delete Expedition', expedition_path(@expedition), class: "btn btn-danger", remote: true, method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></div>
  </div>
</div>