config/routes.rb
Rails.application.routes.draw do
  get 'galaxy_vacansies/search'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :expeditions do
    get 'react', on: :collection
  end
  resources :planets
  resources :spaceships do
    get 'react', on: :collection
  end
  resources :galaxies
  resources :itinerary_entries
  resources :itineraries
  get 'chats/index', to: 'chats#index'
  post 'chats/new_message', to: 'chats#new_message'

  root "expeditions#index"

  scope module: 'api' do
    namespace 'v1' do
      resources :expeditions, only: %I[show index create]
    end
    namespace 'v2' do
      resources :spaceships, only: %I[show index create]
      resources :expeditions
      devise_for :users
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expedition.rb
class Expedition < ApplicationRecord
  has_one :itinerary, dependent: :destroy
  has_many :spaceships, dependent: :destroy
  has_many :users

  validates :title, :description, presence: true
  validates :title, length: { in: 5..50 }
  validates :description, length: { in: 10..500 }

  after_create :create_assocs

  private

  def create_assocs
    create_itinerary(distance: 0.0)
  end
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
  validates :title, presence: true, length: { in: 5..20 }
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :expedition

  has_many :itinerary_entries, dependent: :destroy
  has_many :planets, :through => :itinerary_entries

  def distance_length
    self[:distance].to_f > 0 ? self[:distance].to_f : planets.sum(:distance)
  end
end

app/models/itinerary_entry.rb
class ItineraryEntry < ApplicationRecord
  belongs_to :itinerary
  belongs_to :planet

  validates :value, presence: true, numericality: { greater_than_or_equal_to: 1 }, uniqueness: true
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :itinerary_entries
  has_many :itineraries, :through => :itinerary_entries

  validates :title, :description, :galaxy, :distance, presence: true
  validates :title, length: { maximum: 15 }
  validates :galaxy, length: { maximum: 20 }
  validates :description, length: { in: 10..500 }
  validates :distance, numericality: { greater_than_or_equal_to: 0 }

  scope :accessible, -> { where(available: true) }
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :expedition

  validates :velocity, numericality: { greater_than_or_equal_to: 1 }
  validates :title, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %I[cosmonaut commandor]

  belongs_to :expedition, optional: true
  accepts_nested_attributes_for :expedition
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  after_action :send_message, only: :new_message
  def index; end

  def new_message
    @message = params[:message_input]
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def send_message
    ActionCable.server.broadcast ChatsChannel::TITLE,
                                 action: :new_message.to_s,
                                 message: @message,
                                 user: current_user.email
  end
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  before_action :set_galaxy, except: [:new, :create, :index]

  def new
    @galaxy = Galaxy.new
  end

  def create
    @galaxy = Galaxy.new(galaxy_params)
    if @galaxy.save
      redirect_to galaxies_path, notice: 'Сохранение прошло успешно'
    else
      flash[:alert] = 'Во время сохранения произошли ошибки'
      render :new
    end
  end

  def index
    @galaxies = Galaxy.all
  end

  def edit
  end

  def update
    if @galaxy.update galaxy_params
      redirect_to galaxy_path, notice: 'Successfully saved'
    else
      flash[:alert] = 'Errors appeared while saving'
      render :edit
    end
  end

  def destroy
    @galaxy.destroy
    if @galaxy.destroyed?
      flash[:notice] = 'Destroyed successfully'
    else
      flash[:alert] = 'Error appeared while destroying'
    end
    redirect_to galaxies_path
  end

  def show
  end

  private

  def galaxy_params
    params.require(:galaxy).permit(:title)
  end

  def set_galaxy
    @galaxy = Galaxy.find(params[:id])
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, except: [:new, :create, :index]
  def index
    @planets = Planet.all
  end

  def show
    @planet.itineraries.each do |itinerary|
      @expedition = itinerary.expedition
    end
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    if @planet.save
      redirect_to planets_path, notice: 'Сохранение прошло успешно'
    end
    else
      flash[:alert] = 'Во время сохранения произошли ошибки'
      render :new
    end

  def edit
  end

  def update
    if @planet.update planet_params
      redirect_to planets_path, notice: 'Сохранение прошло успешно'
    else
      flash[:alert] = 'Во время сохранения произошли ошибки'
      render :edit
    end
  end

  def destroy
    @planet.destroy
    if @planet.destroyed?
      flash[:notice] = 'Удалено'
    else
      flash[:alert] = 'Ошибка удаления'
    end
    redirect_to planets_path
  end

  private

  def set_planet
    @planet = Planet.find(params[:id])
  end

  def planet_params
    params.require(:planet).permit(:title, :galaxy, :description, :distance)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/expedition_helper.rb
module ExpeditionHelper
end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/helpers/galaxy_vacansies_helper.rb
module GalaxyVacansiesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/spaceship_helper.rb
module SpaceshipHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetExpedition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .dropdown:hover .dropdown-menu {
        display: block;
      }
    </style>
  </head>

  <body>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <!--    <div class="alert alert-warning alert-dismissible fade show" role="alert">-->
<!--      Список экспедиций-->
<!--      <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--        <span aria-hidden="true">&times;</span>-->
<!--      </button>-->
<!--    </div>-->

    <% if (6..18).member?(Time.now.hour) %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <% else %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <% end %>
    <button class="navbar-toggler nav-link dropdown-toggle" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span>Expeditions menu</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/planets">Планеты</a>
        </li>
        <% if user_signed_in? %>
          <li>
            <a class="nav-link" href="/galaxies">Галактики</a>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Экспедиции
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/expeditions">Список</a>
            <a class="dropdown-item" href="/spaceships">Космические корабли</a>
            <a class="dropdown-item" href="#">Команды</a>
          </div>
        <li>
          <%= link_to 'Вакансии', galaxy_vacansies_search_path, class: 'nav-link' %>
        </li>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
    </nav>

    <%= render 'chats/index' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_slider.html.erb
<div id="slider">
  <%= image_tag('slider/slide1.jpg', alt: 'slide',
                id: 'slide', style: 'width: 1024px; height: 578px;') %>
  <div style="text-align: center">
    <%= link_to '<<', '#', class: 'btn btn-info', id: 'slide-left' %>
    <%= link_to '>>', '#', class: 'btn btn-info', id: 'slide-right' %>
  </div>
</div>